name: Build Firmware

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [air_firmware_esp32cam, air_firmware_esp32s3sense, air_firmware_esp32s3sense_ov5640]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install required Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install PlatformIO lastest
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build firmware
      run: |
        platformio run -d ${{ matrix.project }}

    - name: Upload firmware binaries
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}
        path: |
          ${{ matrix.project }}/.pio/build/**/bootloader.bin
          ${{ matrix.project }}/.pio/build/**/firmware.bin
          ${{ matrix.project }}/.pio/build/**/flash_args
          ${{ matrix.project }}/.pio/build/**/partitions.bin
          ${{ matrix.project }}/.pio/build/**/ota_data_initial.bin
